-- MySQL Script generated by MySQL Workbench
-- Sun Mar 22 00:17:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartao` (
  `idcartao` INT NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `data_validade` DATE NOT NULL,
  `nome_pessoa` VARCHAR(45) NOT NULL,
  `cvv` MEDIUMINT(3) NOT NULL,
  `tipo` ENUM('credito', 'debito') NOT NULL,
  `banco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcartao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`boleto` (
  `idboleto` INT NOT NULL,
  `numero` VARCHAR(50) NOT NULL,
  `data_validade` DATE NOT NULL,
  `data_emissao` DATE NOT NULL,
  PRIMARY KEY (`idboleto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cheque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cheque` (
  `idcheque` INT NOT NULL,
  `banco` VARCHAR(45) NOT NULL,
  `agencia` VARCHAR(45) NOT NULL,
  `numero_conta` VARCHAR(45) NOT NULL,
  `numero_cheque` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcheque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deposito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deposito` (
  `iddeposito` INT NOT NULL,
  `banco` VARCHAR(45) NOT NULL,
  `agencia` VARCHAR(45) NOT NULL,
  `conta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddeposito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`forma_pagamento` (
  `idforma_pagamento` INT NOT NULL,
  `cartao_idcartao` INT NOT NULL,
  `boleto_idboleto` INT NOT NULL,
  `cheque_idcheque` INT NOT NULL,
  `deposito_iddeposito` INT NOT NULL,
  PRIMARY KEY (`idforma_pagamento`),
  INDEX `fk_forma_pagamento_cartao1_idx` (`cartao_idcartao` ASC) VISIBLE,
  INDEX `fk_forma_pagamento_boleto1_idx` (`boleto_idboleto` ASC) VISIBLE,
  INDEX `fk_forma_pagamento_cheque1_idx` (`cheque_idcheque` ASC) VISIBLE,
  INDEX `fk_forma_pagamento_deposito1_idx` (`deposito_iddeposito` ASC) VISIBLE,
  CONSTRAINT `fk_forma_pagamento_cartao1`
    FOREIGN KEY (`cartao_idcartao`)
    REFERENCES `mydb`.`cartao` (`idcartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forma_pagamento_boleto1`
    FOREIGN KEY (`boleto_idboleto`)
    REFERENCES `mydb`.`boleto` (`idboleto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forma_pagamento_cheque1`
    FOREIGN KEY (`cheque_idcheque`)
    REFERENCES `mydb`.`cheque` (`idcheque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forma_pagamento_deposito1`
    FOREIGN KEY (`deposito_iddeposito`)
    REFERENCES `mydb`.`deposito` (`iddeposito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`valor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`valor` (
  `idvalor` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `comissao` FLOAT NOT NULL,
  `forma_pagamento_idforma_pagamento` INT NOT NULL,
  PRIMARY KEY (`idvalor`),
  INDEX `fk_valor_forma_pagamento1_idx` (`forma_pagamento_idforma_pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_valor_forma_pagamento1`
    FOREIGN KEY (`forma_pagamento_idforma_pagamento`)
    REFERENCES `mydb`.`forma_pagamento` (`idforma_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `idendereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `endereco_idendereco` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_endereco1_idx` (`endereco_idendereco` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_endereco1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `mydb`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `estado_civil` VARCHAR(45) NOT NULL,
  `profissão` VARCHAR(45) NOT NULL,
  `tipo` ENUM('proprientario', 'usuario') NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_proprietario` (
  `idcliente_proprietario` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idcliente_proprietario`),
  INDEX `fk_cliente_proprietario_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_proprietario_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`imovel` (
  `idimovel` INT NOT NULL,
  `data_construcao` DATE NOT NULL,
  `categora` INT NOT NULL,
  `data_anuncio` DATE NOT NULL,
  `imovelcol` VARCHAR(45) NOT NULL,
  `status_locacao` TINYINT NOT NULL,
  `status_venda` TINYINT NOT NULL,
  `cliente_proprietario_idcliente_proprietario` INT NOT NULL,
  `endereco_idendereco` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idimovel`),
  INDEX `fk_imovel_cliente_proprietario1_idx` (`cliente_proprietario_idcliente_proprietario` ASC) VISIBLE,
  INDEX `fk_imovel_endereco1_idx` (`endereco_idendereco` ASC) VISIBLE,
  CONSTRAINT `fk_imovel_cliente_proprietario1`
    FOREIGN KEY (`cliente_proprietario_idcliente_proprietario`)
    REFERENCES `mydb`.`cliente_proprietario` (`idcliente_proprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_endereco1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `mydb`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_usuario` (
  `idcliente_imovel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idcliente_imovel`),
  INDEX `fk_cliente_imovel_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_imovel_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locacao` (
  `idlocacao` INT NOT NULL,
  `data_alugado` DATE NOT NULL,
  `valor_idvalor` INT NOT NULL,
  `imovel_idimovel` INT NOT NULL,
  `cliente_imovel_idcliente_imovel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idlocacao`),
  INDEX `fk_locacao_valor1_idx` (`valor_idvalor` ASC) VISIBLE,
  INDEX `fk_locacao_imovel1_idx` (`imovel_idimovel` ASC) VISIBLE,
  INDEX `fk_locacao_cliente_imovel1_idx` (`cliente_imovel_idcliente_imovel` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mydb`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`foto` (
  `idfoto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `imovel_idimovel` INT NOT NULL,
  PRIMARY KEY (`idfoto`),
  INDEX `fk_foto_imovel1_idx` (`imovel_idimovel` ASC) VISIBLE,
  CONSTRAINT `fk_foto_imovel1`
    FOREIGN KEY (`imovel_idimovel`)
    REFERENCES `mydb`.`imovel` (`idimovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`casa` (
  `idcasa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quartos` INT NOT NULL,
  `suites` INT NOT NULL,
  `sala_estar` INT NOT NULL,
  `sala_jantar` INT NOT NULL,
  `vagas_garagem` INT NOT NULL,
  `area` FLOAT NOT NULL,
  `armario` TINYINT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `imovel_idimovel` INT NOT NULL,
  PRIMARY KEY (`idcasa`),
  INDEX `fk_casa_imovel1_idx` (`imovel_idimovel` ASC) VISIBLE,
  CONSTRAINT `fk_casa_imovel1`
    FOREIGN KEY (`imovel_idimovel`)
    REFERENCES `mydb`.`imovel` (`idimovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apartamento` (
  `idapartamento` INT NOT NULL,
  `quartos` INT NULL,
  `suites` INT NULL,
  `sala_estar` INT NULL,
  `sala_jantar` INT NULL,
  `vagas_garagem` INT NULL,
  `area` FLOAT NULL,
  `armario` TINYINT NULL,
  `descricao` VARCHAR(45) NULL,
  `andar` INT NULL,
  `valor_condominio` FLOAT NULL,
  `portaria_24hrs` TINYINT NULL,
  `numero_apartamento` INT NULL,
  `imovel_idimovel` INT NOT NULL,
  PRIMARY KEY (`idapartamento`),
  INDEX `fk_apartamento_imovel1_idx` (`imovel_idimovel` ASC) VISIBLE,
  CONSTRAINT `fk_apartamento_imovel1`
    FOREIGN KEY (`imovel_idimovel`)
    REFERENCES `mydb`.`imovel` (`idimovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`terreno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`terreno` (
  `idterreno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `area` FLOAT NOT NULL,
  `largura` FLOAT NOT NULL,
  `comprimento` FLOAT NOT NULL,
  `aclive/declive` TINYINT NOT NULL,
  `imovel_idimovel` INT NOT NULL,
  PRIMARY KEY (`idterreno`),
  INDEX `fk_terreno_imovel1_idx` (`imovel_idimovel` ASC) VISIBLE,
  CONSTRAINT `fk_terreno_imovel1`
    FOREIGN KEY (`imovel_idimovel`)
    REFERENCES `mydb`.`imovel` (`idimovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sala_comercial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sala_comercial` (
  `idsala_comercial` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `area` FLOAT NOT NULL,
  `banheiro` INT NOT NULL,
  `comodos` INT NOT NULL,
  `imovel_idimovel` INT NOT NULL,
  PRIMARY KEY (`idsala_comercial`),
  INDEX `fk_sala_comercial_imovel1_idx` (`imovel_idimovel` ASC) VISIBLE,
  CONSTRAINT `fk_sala_comercial_imovel1`
    FOREIGN KEY (`imovel_idimovel`)
    REFERENCES `mydb`.`imovel` (`idimovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `idvenda` INT NOT NULL,
  `data_venda` DATE NOT NULL,
  `valor_idvalor` INT NOT NULL,
  `imovel_idimovel` INT NOT NULL,
  `cliente_imovel_idcliente_imovel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_venda_valor1_idx` (`valor_idvalor` ASC) VISIBLE,
  INDEX `fk_venda_imovel1_idx` (`imovel_idimovel` ASC) VISIBLE,
  INDEX `fk_venda_cliente_imovel1_idx` (`cliente_imovel_idcliente_imovel` ASC) VISIBLE,
  CONSTRAINT `fk_venda_valor1`
    FOREIGN KEY (`valor_idvalor`)
    REFERENCES `mydb`.`valor` (`idvalor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_imovel1`
    FOREIGN KEY (`imovel_idimovel`)
    REFERENCES `mydb`.`imovel` (`idimovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente_imovel1`
    FOREIGN KEY (`cliente_imovel_idcliente_imovel`)
    REFERENCES `mydb`.`cliente_usuario` (`idcliente_imovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `idcargo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `salario` FLOAT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `idfuncionario` INT NOT NULL,
  `data_ingresso` DATE NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(128) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `cargo_idcargo` INT NOT NULL,
  `locacao_idlocacao` INT NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  INDEX `fk_funcionario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_funcionario_cargo1_idx` (`cargo_idcargo` ASC) VISIBLE,
  INDEX `fk_funcionario_locacao1_idx` (`locacao_idlocacao` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_cargo1`
    FOREIGN KEY (`cargo_idcargo`)
    REFERENCES `mydb`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_locacao1`
    FOREIGN KEY (`locacao_idlocacao`)
    REFERENCES `mydb`.`locacao` (`idlocacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `idtelefone` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idtelefone`),
  INDEX `fk_telefone_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fiador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fiador` (
  `idfiador` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cliente_imovel_idcliente_imovel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idfiador`),
  INDEX `fk_fiador_cliente_imovel_idx` (`cliente_imovel_idcliente_imovel` ASC) VISIBLE,
  CONSTRAINT `fk_fiador_cliente_imovel`
    FOREIGN KEY (`cliente_imovel_idcliente_imovel`)
    REFERENCES `mydb`.`cliente_usuario` (`idcliente_imovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`indicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`indicacao` (
  `idindicacao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `cliente_imovel_idcliente_imovel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idindicacao`),
  INDEX `fk_indicacao_cliente_imovel1_idx` (`cliente_imovel_idcliente_imovel` ASC) VISIBLE,
  CONSTRAINT `fk_indicacao_cliente_imovel1`
    FOREIGN KEY (`cliente_imovel_idcliente_imovel`)
    REFERENCES `mydb`.`cliente_usuario` (`idcliente_imovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
